repos:
- hooks:
  - id: check-yaml
  - id: check-toml
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.21.3
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.3.5'
  hooks:
    - id: ruff
    - id: ruff-format
