repos:
- hooks:
  - id: check-yaml
  - id: check-toml
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: black
    language_version: python3.8
  repo: https://github.com/psf/black
  rev: 23.7.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: 3.5.3
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.278'
  hooks:
    - id: ruff
      # Respect `exclude` and `extend-exclude` settings.
