repos:
- hooks:
  - id: check-yaml
  - id: check-toml
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: black
    language_version: python3.10
  repo: https://github.com/psf/black
  rev: 22.6.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.0
