# Creating a release in GitHub will trigger an upload to PyPI and
# uploaded the sdist (source distribution) to the release.
name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.7"
      - name: "Install dependencies"
        run: |
          set -xe
          python3 -VV
          python3 -m site
          python3 -m pip install --upgrade pip build
      - name: "Build package"
        run: |
          python3 -m build
      - name: "Publish package to PyPI"
        uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: "Get release"
        id: get_release
        uses: bruceadams/get-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: "Get Asset name"
        run: |
          export PKG=$(ls dist/ | grep tar)
          set -- $PKG
          echo "name=$1" >> $GITHUB_ENV
      - name: "Upload Release Asset (sdist) to GitHub Release"
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist/${{ env.name }}
          asset_name: ${{ env.name }}
          asset_content_type: application/zip
